version: '3.8'

# This is a master docker-compose file that includes all other compose files
# You can still use the individual files for more granular control

# To start all services:
# docker-compose up -d

# To start only specific stacks:
# docker-compose -f docker-compose.mongo.yml -f docker-compose.kafka.yml up -d

services:

  # API (from docker-compose.api.yml)
  e-commerce-api:
    extends:
      file: docker-compose.api.yml
      service: e-commerce-api

  # UI (from docker-compose.ui.yml)
  e-commerce-ui:
    extends:
      file: docker-compose.ui.yml
      service: e-commerce-ui
