version: '3.8'

services:
  # MongoDB
  mongo:
    image: mongo
    container_name: eCommerce-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: [ "CMD-SHELL", "mongosh --eval \"db.runCommand({ping:1}).ok\" --quiet" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # MongoDB Express (Web UI)
  mongo-express:
    image: mongo-express
    container_name: eCommerce-mongo-express
    restart: always
    ports:
      - "8085:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongo:27017/
    depends_on:
      mongo:
        condition: service_healthy

volumes:
  mongo-data:
